phantomjs

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -9,7 +9,111 @@ build_dir=$1
 cache_dir=$2
 env_dir=$3
 
+LP_DIR=`cd $(dirname $0); cd ..; pwd`
+
 bp_dir=$(cd $(dirname $0); cd ..; pwd)
+
+S3_BUCKET="heroku-buildpack-nodejs"
+
+
+
+function error() {
+  echo " !     $*" >&2
+  exit 1
+}
+
+function mktmpdir() {
+  dir=$(mktemp -t node-$1-XXXX)
+  rm -rf $dir
+  mkdir -p $dir
+  echo $dir
+}
+
+function indent() {
+  c='s/^/       /'
+  case $(uname) in
+    Darwin) sed -l "$c";;
+    *)      sed -u "$c";;
+  esac
+}
+
+function run_npm() {
+  command="$1"
+
+  cd $build_dir
+  HOME="$build_dir" $VENDORED_NODE/bin/node $VENDORED_NPM/cli.js $command 2>&1 | indent
+
+  if [ "${PIPESTATUS[*]}" != "0 0" ]; then
+    echo " !     Failed to $command dependencies with npm"
+    exit 1
+  fi
+}
+
+function manifest_versions() {
+  curl "http://${S3_BUCKET}.s3.amazonaws.com/manifest.${1}" -s -o - | tr -s '\n' ' '
+}
+
+function resolve_version() {
+  available_versions="$1"
+  requested_version="$2"
+  default_version="$3"
+
+  if [ "$2" == "" ]; then
+    echo $3
+  else
+    args=""
+    for version in $available_versions; do args="${args} -v \"${version}\""; done
+    for version in $requested_version; do args="${args} -r \"${version}\""; done
+    evaluated_version=$(eval $bootstrap_node/bin/node $LP_DIR/vendor/node-semver/bin/semver ${args} || echo "")
+    echo "$evaluated_version" | tail -n 1
+  fi
+}
+
+function package_engine_version() {
+  version=$(cat $build_dir/package.json | $bootstrap_node/bin/node $LP_DIR/vendor/json/json engines.$1 2>/dev/null)
+  if [ $? == 0 ]; then
+    echo $version | sed -e 's/\([<>=]\) /\1/g'
+  fi
+}
+
+function package_resolve_version() {
+  engine="$1"
+  resolved_version=$(resolve_version "${engine_versions[$engine]}" "${engine_requests[$engine]}" "${engine_defaults[$engine]}")
+
+  if [ "${resolved_version}" == "" ]; then
+    error "Requested engine $engine version ${engine_requests[$engine]} does not match available versions: ${engine_versions[$engine]}"
+  else
+    echo $resolved_version
+  fi
+}
+
+function package_download() {
+  engine="$1"
+  version="$2"
+  location="$3"
+
+  mkdir -p $location
+  package="http://${S3_BUCKET}.s3.amazonaws.com/$engine-$version.tgz"
+  curl $package -s -o - | tar xzf - -C $location
+}
+
+function download() {
+  src="$1"
+  location="$2"
+
+  mkdir -p $location
+  curl $src -s -o - | tar xzf - -C $location
+}
+
+# make some associative arrays
+declare -A engine_versions
+declare -A engine_defaults
+declare -A engine_requests
+
+
+engine_defaults["phantom"]="1.4.1"
+engine_versions["phantom"]=$(manifest_versions "phantomjs")
+engine_requests["phantom"]=$(package_engine_version "phantom")
 
 # Load some convenience functions like status(), echo(), and indent()
 source $bp_dir/bin/common.sh
@@ -170,10 +274,29 @@ fi
   fi
 )
 
+
+PHANTOMJS_VERSION=$(package_resolve_version "phantom")
+echo "Using Phantom.js version: ${PHANTOMJS_VERSION}" | indent
+
+PHANTOMJS_PACKAGE="http://journalismpp.s3.amazonaws.com/phantomjs-${PHANTOMJS_VERSION}.tgz"
+
+VENDORED_PHANTOMJS="$(mktmpdir phantom)"
+
+echo "-----> Fetching Phantom.js binaries"
+download "${PHANTOMJS_PACKAGE}" "${VENDORED_PHANTOMJS}"
+
 # Update the PATH
 status "Building runtime environment"
 mkdir -p $build_dir/.profile.d
 echo "export PATH=\"\$HOME/vendor/node/bin:\$HOME/bin:\$HOME/node_modules/.bin:\$PATH\";" > $build_dir/.profile.d/nodejs.sh
+
+echo "-----> Building Phantom.js environment"
+# for phantomjs
+mkdir -p $build_dir/bin
+curl https://raw.github.com/gist/1983913/phantomjs.sh -s -o $build_dir/bin/phantomjs.sh
+chmod 755 $build_dir/bin/phantomjs.sh
+curl https://raw.github.com/gist/1983751/phantomexec.sh -s -o $build_dir/bin/phantomexec.sh
+chmod 755 $build_dir/bin/phantomexec.sh
 
 # Post package.json to nomnom service
 # Use a subshell so failures won't break the build.
@@ -187,3 +310,5 @@ echo "export PATH=\"\$HOME/vendor/node/bin:\$HOME/bin:\$HOME/node_modules/.bin:\
     https://nomnom.heroku.com/?request_id=$REQUEST_ID \
     > /dev/null
 ) &
+
+echo "COOL"
